### ISSUE TITLE
Missing landmark embedding & uv template files

### ISSUE THREAD

**Issue by jerrymatjila** [Zielon/metrical-tracker#1]
Thanks for releasing long awaited face tracking.
I noticed the following files are missing.

```bash
'data/uv_template.obj'
'data/landmark_embedding.npy'
'data/uv_mask_eyes.png'
```

Can you kindly provide guidelines how to generate/get those files?

**Comment by Zielon** [comment]
You can use `install.sh` script do download all of the necessary files. Alternatively, `wget -O mesh.zip "https://keeper.mpdl.mpg.de/f/f158a430ef754edba5ec/?dl=1"`
