### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by 1-w-m** [Zielon/metrical-tracker#10]
Dear author, I have three questions to ask you.
1、May I ask if the camera parameters returned are camera parameters for each frame？
2、What is the model obtained after training used for？
3、How to obtain corresponding camera parameters from photos？

**Comment by Zielon** [comment]
Yes, camera is saved for each frame. Take a look herehttps://github.com/Zielon/metrical-tracker/blob/be8ab0aea38841ca6f0e3e90afb914871137fb35/tracker.py#LL183C1-L183C1

**Comment by 1-w-m** [comment]
Sorry, I have another question. Can I obtain camera parameters from a photo instead of a video?
