### ISSUE TITLE
rotation matrix

### ISSUE THREAD

**Issue by 1-w-m** [Zielon/metrical-tracker#11]
Why the value in the returned camera parameter's rotation matrix is greater than 1？

{'R': array([[-1.4803067 , -0.02659582,  0.13538209, -0.4449267 ,  1.4254882 ,
        -0.05706715]], dtype=float32), 't': array([[-0.00678921,  0.02268134,  1.114467  ]], dtype=float32), 'fl': array([[9.188737]], dtype=float32), 'pp': array([[-0.00433624,  0.02280937]], dtype=float32)}

**Comment by Zielon** [comment]
This is a 6D rotation. You can use [6D to matrix](https://pytorch3d.readthedocs.io/en/latest/modules/transforms.html#pytorch3d.transforms.rotation_6d_to_matrix) to change the representation.
