### ISSUE TITLE
Long time to generate for 1000 frames

### ISSUE THREAD

**Issue by alchemician** [Zielon/metrical-tracker#14]
optimize color is taking too much time. it took me 1 hr time for 5 second video (~100 frames) on a 6GB GPU

I am planning to use the tracker for the INSTA repo. To generate for 1000 frames, it will take me 10 hours.

any ideas on how to improve speed? @Zielon

**Comment by Zielon** [comment]
You can experiment with the config hyperparameters. For instance set `pyr_levels: [[1.0, 160], [0.25, 40], [0.5, 40], [1.0, 70]]` (this is default one) to different values or remove the amout the levels of Gaussian pyramid, the last three layers. You can try sth like:

```
# Tracker config

actor: 'your/actor/path'
save_folder: './output/'
optimize_shape: true
optimize_jaw: true
begin_frames: 1
keyframes: [ 0, 1 ]
pyr_levels: [[1.0, 100], [0.5, 40], [1.0, 40]]
```

**Comment by emlcpfx** [comment]
I see a speed improvement by removing a level of Gaussian pyramid, like in your example. But why did you change the other values to-from:

[1.0, 160], [0.25, 40], [0.5, 40]
[1.0, 100], [0.5, 40], [1.0, 40]

What do each of these sets of numbers mean?

Is there any setting that keeps a better track quality than EMOCA at a similar speed to that tracker?
