### ISSUE TITLE
UV_texture

### ISSUE THREAD

**Issue by zjxcc** [Zielon/metrical-tracker#15]
I want to know how to obtain UV texture. I can only get the rendered image, and I don't know where to find colored vertices? I am a beginner and look forward to receiving your reply. Thank you.

**Comment by Zielon** [comment]
You can obtain the texture from the parametric model. Here is the code https://github.com/Zielon/metrical-tracker/blob/master/flame/FLAME.py#L309.

**Comment by Haobo-Liu** [comment]
> You can obtain the texture from the parametric model. Here is the code https://github.com/Zielon/metrical-tracker/blob/master/flame/FLAME.py#L309.

How to implement?
