### ISSUE TITLE
Vertices coordinate

### ISSUE THREAD

**Issue by RIA1159** [Zielon/metrical-tracker#16]
How can I get the vertices  coordinate of the flame head model ?
The vertices in tracker.py#L482 is a normalized result which can not be mapped to the image. 
I amplify this vertices by multiply it by 512 which gives the results like this:
![test](https://github.com/Zielon/metrical-tracker/assets/52986216/bc49bf9b-6b84-4069-91a7-64bbabf5a56b)

How can I get the vertices coordinate which aligned to the face like this:
![0002](https://github.com/Zielon/metrical-tracker/assets/52986216/bba287f3-1b0a-43a0-a98a-91ec84b26da5)

**Comment by Zielon** [comment]
You can use [transform_points_screen()](https://pytorch3d.readthedocs.io/en/latest/_modules/pytorch3d/renderer/cameras.html#CamerasBase.transform_points_screen) from pytroch3d. For instance, [here](https://github.com/Zielon/metrical-tracker/blob/c2a517244759d7eeaa0e84893d6748e75293f81a/tracker.py#L579C1-L579C1) replace `lmk68` with `vertices`.

**Comment by RIA1159** [comment]
![test](https://github.com/Zielon/metrical-tracker/assets/52986216/c8fac54e-34bf-424e-a0f9-3384008ff19d)
This works!  Thanks a lot!
