### ISSUE TITLE
Speed > Quality Tuning

### ISSUE THREAD

**Issue by emlcpfx** [Zielon/metrical-tracker#18]
Aside from the pyr levels are there other settings we can tweak to squeeze out more performance at the sacrifice of a perfect track?

**Comment by Zielon** [comment]
You could optimize lower resolution for instance. 256x256 images that should give speedup. Pyr levels and the number of steps per level can also be reduced.

**Comment by emlcpfx** [comment]
I tried changing cfg.image_size = [512, 512] to 256x256, and got an error.

Am I supposed to change a different parameter to get the 256 images you mentioned above? Thank you!

**Comment by Zielon** [comment]
What if you set `pyr_levels: [[1.0, 160], [0.5, 40]]`. The first element in the array is only for keypoint optimization the next one is Gaussian pyr levels. Here you will do 1.0 original resolution (let's assume 512x512) for sparse/keypoint term and 256x256, 40 times for dense term.

**Comment by emlcpfx** [comment]
I can get it to EMOCA V2 speeds. I was irrationally hoping to get that quality of track at 3DDFA_V2 speeds.

(I’m on a Ryzen 5800X and RTX 3090.)

**Comment by larsh0103** [comment]
@emlcpfx What speeds are we talking and how did you make that happen, just applying the image downscaling and changing the pyramid levels?

**Comment by emlcpfx** [comment]
@larsh0103 yes, just by changing the values above. The problem was, I could get it down to EMOCA speeds, but then EMOCA was more accurate, and I already had a workflow built around it. Didn’t make sense to port it to MICA.

**Comment by larsh0103** [comment]
> @larsh0103 yes, just by changing the values above. The problem was, I could get it down to EMOCA speeds, but then EMOCA was more accurate, and I already had a workflow built around it. Didn’t make sense to port it to MICA.

Gotcha! Thanks for letting me know!

**Comment by jimydavis** [comment]
@emlcpfx are you getting something like 4 to 5 seconds per frame with MICA? 

So for example, 1000 frames would take about 1.3 hours.  1000 frames @ 30fps is a 33 second video. 

Do you know of any other trackers that are faster even for a slightly lower quality?

Thank you for the help!

**Comment by emlcpfx** [comment]
@jimydavis EMOCA and SMIRK are both faster. 3DDFA-V3 is really fast & accurate too, but it uses the Basel Face Model instead of FLAME.

**Comment by jimydavis** [comment]
@emlcpfx thanks! I tried 3DDFA-V2 (havent tried V3) and it was something like 20FPS but MICA was 0.2FPS, almost a 100x difference. I don't fully understand why either. Is EMOCA / SMIRK in the same <1FPS ball park for you too?

**Comment by emlcpfx** [comment]
I don’t remember the fps, but I could do a test if you send the footage you’re benchmarking.

**Comment by jimydavis** [comment]
Thank you but I was just looking for a ballpark on whether it was off by 10x or 100x. Thank you!

**Comment by emlcpfx** [comment]
Depends on the settings. Easily 10x, and that gives very nice quality.

**Comment by emlcpfx** [comment]
I did a test today on a 160 frame shot. 19 minutes with Metrical Tracker, SMIRK 30 seconds. Very similar results.
