### ISSUE TITLE
Why apply gaussian blur to pyramid images?

### ISSUE THREAD

**Issue by chenerg** [Zielon/metrical-tracker#21]
I'm confued about the gaussian blur operation applied during get_gaussian_pyramid function;  I think adding blur only generate less accurate results. Would you please provide some explanation?

**Comment by Zielon** [comment]
To improve optimization and avoid local minima, you can apply a low pass filter on the image, effectively removing high-frequency details (for instance, edges). Doing it progressively using a pyramid stabilizes the optimization. Besides, BFM texture space has only low-frequency information.
