### ISSUE TITLE
how to get the best identity.npy

### ISSUE THREAD

**Issue by DestoryVIP** [Zielon/metrical-tracker#25]
Thanks for your wonderful work, I have a question about how to get the best identity.npy file in one video, please ask how to get the best identity.npy in one video?

**Comment by HarshWinterBytes** [comment]
I have the same question. Did you find the solution?

**Comment by Zielon** [comment]
I selected a frame with a neutral face, however, you could also select a random one or the first one.

**Comment by HarshWinterBytes** [comment]
> I selected a frame with a neutral face, however, you could also select a random one or the first one.

thanks for your early reply
