### ISSUE TITLE
lmk 

### ISSUE THREAD

**Issue by Tiandishihua** [Zielon/metrical-tracker#30]
lmk_path = imagepath.replace('images', 'kpt').replace('.png', '.npy').replace('.jpg', '.npy')  is  kpt7.npy ?
lmk_path_dense = imagepath.replace('images', 'kpt_dense').replace('.png', '.npy').replace('.jpg', '.npy') is kpt68.npy?

**Comment by Zielon** [comment]
lmk_path is 68 lmk from `pip install face-recognition`
lmk_path_dense is 468 (I think) from mediapipe package

**Comment by Tiandishihua** [comment]
> lmk_path is 68 lmk from `pip install face-recognition` lmk_path_dense is 468 (I think) from mediapipe package

With MICA, have you successfully run metrical-tracker？
