### ISSUE TITLE
About output jaw 

### ISSUE THREAD

**Issue by buptzz** [Zielon/metrical-tracker#32]
I have read the paper on MICA, but I am somewhat unclear about the meaning of the jaw coefficients in the output results. Can I interpret them as representing lip movements? Are the exp coefficients standard FLAME coefficients? If so, do they not include actions of the lips/jaw?

**Comment by Zielon** [comment]
Jaw joint open and closes the jaw. It has no influence on the lips movement. This part is represented by expressions.
