### ISSUE TITLE
from whihc frame to compite identity.npy

### ISSUE THREAD

**Issue by haithemb** [Zielon/metrical-tracker#5]
"identity.npy" is needed to be computed from MICA. But MICA produces different "identity.npy" files equal the number of frames. Which one to choose for the tracker? Thanks!

**Comment by Zielon** [comment]
The best identity.npy is for a frame that has a neutral pose.

**Comment by DestoryVIP** [comment]
how to get the best identity? i don't know how to calculate pleaes?

> 最好的 identity.npy 适用于具有中性姿势的框架。
