### ISSUE TITLE
Why the total frame number of my input video is 613, but there are only 513 frames in the source folder

### ISSUE THREAD

**Issue by duan348733684** [Zielon/metrical-tracker#7]
Hi~ Thanks a lot for your great work.

Why the total frame number of my input video is 613, but there are only 513 frames in the "source" folder？

**Comment by RIA1159** [comment]
> Hi~ Thanks a lot for your great work.
> 
> Why the total frame number of my input video is 613, but there are only 513 frames in the "source" folder？

Same question here
