### ISSUE TITLE
 Why modifying the  batch_size cannot improve the speed

### ISSUE THREAD

**Issue by duan348733684** [Zielon/metrical-tracker#8]
Hi~ Thanks a lot for your great work.

Why modifying the  batch_size cannot improve the speed. 
https://github.com/Zielon/metrical-tracker/blob/master/tracker.py#L688

it's too slow when optimize color.

**Comment by duan348733684** [comment]
https://github.com/Zielon/metrical-tracker/blob/master/tracker.py #L654
can the code be changed to parallel?

**Comment by Zielon** [comment]
The current version supports only sequential processing.

**Comment by pranavmalikk** [comment]
@duan348733684 were you able to speed up this process? It took me 1 hour 15 minutes for the duda video clip! I'm wondering what ways can we speed this process up

**Comment by emlcpfx** [comment]
@pranavmalikk see https://github.com/Zielon/metrical-tracker/issues/18
